version: '3.8'
services:
  app:
    build: .
    image: market-intel-local:latest
    ports:
      - "3000:3000"
    environment:
      - PRIMARY_DATA_PROVIDER=alphavantage
      - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"